importing numpy,pandas,linearregression model


In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

data is in form of y=2x1+3x2+4x3+5

In [ ]:
data=pd.read_csv('data.csv')

In [ ]:
data

x1  x2  x3    y
0 -94  24  22  -23
1  12  63  11  262
2  27  87  23  412
3  56   9   6  168
4  66  12  76  477
5  78   1  53  376
6  25  23  91  488
7  98  43   2  338
8  45  32   0  191
9  21  11   2   88

In [ ]:
x=data[['x1','x2','x3']].values

In [ ]:
x

array([[-94,  24,  22],
       [ 12,  63,  11],
       [ 27,  87,  23],
       [ 56,   9,   6],
       [ 66,  12,  76],
       [ 78,   1,  53],
       [ 25,  23,  91],
       [ 98,  43,   2],
       [ 45,  32,   0],
       [ 21,  11,   2]])

In [ ]:
y=data[['y']].values
y

array([[-23],
       [262],
       [412],
       [168],
       [477],
       [376],
       [488],
       [338],
       [191],
       [ 88]])

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

the intercept of the equation is 5

In [ ]:
model.intercept_

array([5.])

the coefficients of x1=2,x2=3,x3=4

In [ ]:
model.coef_

array([[2., 3., 4.]])

In [ ]:
y_predict=model.predict(x)

In [ ]:
y_predict

array([[-23.],
       [262.],
       [412.],
       [168.],
       [477.],
       [376.],
       [488.],
       [338.],
       [191.],
       [ 88.]])

if x1=3,x2=2,x3=1 then y should be 21 according to the equation y=2x1+3x2+4x3+5

In [ ]:
x_new=np.array([[3,  2,  1]])

In [ ]:
y_new=model.predict(x_new)

In [ ]:
y_new

array([[21.]])